# path: C:/Projects/College Projects/HumanDetection/HumanDetection/dataset
# train: train/images
# val: train/images

# path: C:/Projects/College Projects/HumanDetection/HumanDetection/dataset/thermalHumanImaging/dataset
# train: train/images
# val: train/images

# path: C:/Projects/College Projects/HumanDetection/HumanDetection/dataset_aug
# train: train/images
# val: train/images

path: C:/Projects/College Projects/HumanDetection/HumanDetection/dataset/ship
train: train/images
val: train/images

# path: C:\Projects\College Projects\HumanDetection\HumanDetection\data
# train: train\images
# val: val\images

# path: C:\Projects\College Projects\HumanDetection\HumanDetection\NewData
# train: images
# val: images

#Classes
names:
  0: Human
  1: Torso
  2: Arm
  3: Leg
